specVersion: 0.2.0
name: balances-transfers
version: 1.0.0
description: This is the task from SubQuery HeroCourse. Module3, exercise 1
repository: git@github.com:UsmanAAV/SubQueryModule3Exercize1.git
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
  endpoint: wss://polkadot.api.onfinality.io/public-ws
dataSources:
  - kind: substrate/Runtime
    startBlock: 8005117
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
